/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p47.reto4.vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utp.misiontic2022.c2.p47.reto4.controlador.ControladorRequerimientos;
import utp.misiontic2022.c2.p47.reto4.vista.RetoTM;
import utp.misiontic2022.c2.p47.reto4.vista.RetoTM2;
import utp.misiontic2022.c2.p47.reto4.vista.RetoTM3;
import utp.misiontic2022.c2.p47.reto4.util.JDBCUtilities;
/**
 *
 * @author ASUS
 */
public class Reto4_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Reto4_GUI
     */
    private ControladorRequerimientos controlador;
    private RetoTM retoTM;
    private RetoTM2 retoTM2;
    private RetoTM3 retoTM3;
    
    public Reto4_GUI() {
        initComponents();
        controlador = new ControladorRequerimientos();
      tbTabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_Proyecto", "Ciudad", "Clasificación", "Costo_Proyecto"
            }));
        tbTabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lider", "Cargo", "# Proyectos"
            }));
            tbTabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null}
            },
            new String [] {
                "ID_MaterialConstrucción", "Nombre_Material", "Cantidad", "Precio_Unidad","Precio_Total"
            }));
//        ListarConsulta1();
//        ListarConsulta2();
//        ListarConsulta3();
       
//        setLocation(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpMenu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabla1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        BTN_R1 = new javax.swing.JToggleButton();
        BTNclean = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BDname = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTabla2 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        BTN_R2 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BDname1 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTabla3 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        BTN_3 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BDname2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuSql1 = new javax.swing.JMenuItem();
        jMenuSql2 = new javax.swing.JMenuItem();
        jMenuSql3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SalesPro");
        setIconImage(getIconImage());

        tpMenu.setPreferredSize(new java.awt.Dimension(600, 300));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Información Lideres");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setDividerLocation(35);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel5.setLayout(new java.awt.BorderLayout());

        tbTabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbTabla1);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_R1.setText("Consultar");
        BTN_R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_R1ActionPerformed(evt);
            }
        });
        jPanel6.add(BTN_R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 90, -1));

        BTNclean.setText("Limpiar");
        BTNclean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcleanActionPerformed(evt);
            }
        });
        jPanel6.add(BTNclean, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setRightComponent(jPanel5);

        jPanel7.setEnabled(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("BD");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        BDname.setText("Base de Datos");
        BDname.setEnabled(false);
        BDname.setRequestFocusEnabled(false);
        jPanel7.add(BDname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, -1));

        jSplitPane1.setLeftComponent(jPanel7);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        tpMenu.addTab("Lideres", jPanel1);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Información Materiales");
        jPanel4.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jSplitPane2.setDividerLocation(35);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel8.setLayout(new java.awt.BorderLayout());

        tbTabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbTabla2);

        jPanel8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_R2.setText("Consultar");
        BTN_R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_R2ActionPerformed(evt);
            }
        });
        jPanel9.add(BTN_R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 90, -1));

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jSplitPane2.setRightComponent(jPanel8);

        jPanel10.setEnabled(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("BD");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        BDname1.setText("Base de Datos");
        BDname1.setEnabled(false);
        BDname1.setRequestFocusEnabled(false);
        jPanel10.add(BDname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, -1));

        jSplitPane2.setLeftComponent(jPanel10);

        jPanel4.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        tpMenu.addTab("Materiales", jPanel4);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Información Proyectos");
        jPanel11.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jSplitPane3.setDividerLocation(35);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel12.setLayout(new java.awt.BorderLayout());

        tbTabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbTabla3);

        jPanel12.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_3.setText("Consultar");
        BTN_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_3ActionPerformed(evt);
            }
        });
        jPanel13.add(BTN_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 90, -1));

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        jPanel12.add(jPanel13, java.awt.BorderLayout.PAGE_END);

        jSplitPane3.setRightComponent(jPanel12);

        jPanel14.setEnabled(false);
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("BD");
        jPanel14.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        BDname2.setText("Base de Datos");
        BDname2.setEnabled(false);
        BDname2.setRequestFocusEnabled(false);
        BDname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDname2ActionPerformed(evt);
            }
        });
        jPanel14.add(BDname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, -1));

        jSplitPane3.setLeftComponent(jPanel14);

        jPanel11.add(jSplitPane3, java.awt.BorderLayout.CENTER);

        tpMenu.addTab("Proyectos USD 70000", jPanel11);

        getContentPane().add(tpMenu, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("Opcion");

        jMenuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSalir);

        jMenuBar1.add(jMenu1);

        jMenuConsultas.setText("Ventanas");

        jMenuSql1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuSql1.setText("Lideres");
        jMenuSql1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSql1ActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuSql1);

        jMenuSql2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuSql2.setText("Materiales");
        jMenuSql2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSql2ActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuSql2);

        jMenuSql3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuSql3.setText("Proyectos USD 70000");
        jMenuSql3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSql3ActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuSql3);

        jMenuBar1.add(jMenuConsultas);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private void ListarConsulta1(){
        try{
            var Lista= controlador.consultarRequerimiento1();
            retoTM= new RetoTM(Lista);
//            tbTabla1.setModel(retoTM);
           tbTabla1.setModel(retoTM);
           BDname.setText(JDBCUtilities.getDatabaseLocation());
           
        }
        catch (Exception e){
       
        }
        
    }
         private void ListarConsulta2(){
        try{
            var Lista= controlador.consultarRequerimiento2();
            retoTM2= new RetoTM2(Lista);
//            tbTabla1.setModel(retoTM);
           tbTabla2.setModel(retoTM2);
           BDname1.setText(JDBCUtilities.getDatabaseLocation());
           
        }
        catch (Exception e){
       
        }
        
    }
    private void ListarConsulta3(){
        try{
            var Lista= controlador.consultarRequerimiento3();
            retoTM3= new RetoTM3(Lista);
//            tbTabla1.setModel(retoTM);
           tbTabla3.setModel(retoTM3);
           BDname2.setText(JDBCUtilities.getDatabaseLocation());
           
        }
        catch (Exception e){
       
        }
        
    }
    
        
    private void jMenuSql1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSql1ActionPerformed
        // TODO add your handling code here:
        tpMenu.setSelectedIndex(0);
    }//GEN-LAST:event_jMenuSql1ActionPerformed

    private void jMenuSql2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSql2ActionPerformed
        // TODO add your handling code here:
        tpMenu.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuSql2ActionPerformed

    private void jMenuSql3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSql3ActionPerformed
        // TODO add your handling code here:
        tpMenu.setSelectedIndex(2);
    }//GEN-LAST:event_jMenuSql3ActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        if( JOptionPane.showConfirmDialog(this, "Cerrar", getTitle(),JOptionPane.YES_OPTION)==JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void BTN_R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_R1ActionPerformed
        // TODO add your handling code here:
         ListarConsulta1();
    }//GEN-LAST:event_BTN_R1ActionPerformed

    private void BTN_R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_R2ActionPerformed
        // TODO add your handling code here:
        ListarConsulta2();
    }//GEN-LAST:event_BTN_R2ActionPerformed

    private void BTN_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_3ActionPerformed
        // TODO add your handling code here:
        ListarConsulta3();
    }//GEN-LAST:event_BTN_3ActionPerformed

    private void BDname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BDname2ActionPerformed

    private void BTNcleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcleanActionPerformed
        // TODO add your handling code here:


 tbTabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lider", "Cargo", "# Proyectos"
            }));
//tbTabla1.se
//tbTabla1.removeAll();
//        
    }//GEN-LAST:event_BTNcleanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tbTabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null}
            },
            new String [] {
                "ID_MaterialConstrucción", "Nombre_Material", "Cantidad", "Precio_Unidad","Precio_Total"
            }));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        Integer nc= tbTabla3.getColumnCount();
//        
//        String FilasVacias []= new String[4];        
                
//        retoTM3= new RetoTM3();
        tbTabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_Proyecto", "Ciudad", "Clasificación", "Costo_Proyecto"
            }));
          
//tbTabla3.setModel(retoTM3);
//tbTabla3.addColumn(FilasVacias);







         
    }//GEN-LAST:event_jButton1ActionPerformed
//@Override public Image getIconImage() {
//        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("C:\\Users\\ASUS\\OneDrive\\Documentos\\reto4_p47_plantilla\\src\\main\\java\\utp\\misiontic2022\\c2\\p47\\reto4\\beorchoose_ico_2.ico"));
//        return retValue;
//    }
    @Override
public Image getIconImage() {
//   Image retValue = Toolkit.getDefaultToolkit().
//         getImage(ClassLoader.getSystemResource("resources/icono.png"));
Image retValue = Toolkit.getDefaultToolkit().getImage("C:\\Users\\ASUS\\OneDrive\\Documentos\\reto5_p47_boc\\src\\main\\java\\utp\\misiontic2022\\c2\\p47\\reto4\\beorchoose_ico.png");
//Image retValue = Toolkit.getDefaultToolkit().getImage("C:\\Users\\ASUS\\OneDrive\\Documentos\\reto4_p47_plantilla\\src\\main\\java\\utp\\misiontic2022\\c2\\p47\\reto4\\beorchoose_ico_2.ico");
   return retValue;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reto4_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reto4_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reto4_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reto4_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reto4_GUI().setVisible(true);
//                ImageIcon img = new ImageIcon("turuta");
////define el icon a tu JFrame
//                  tuFrame.setIconImage(img.getImage());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BDname;
    private javax.swing.JTextField BDname1;
    private javax.swing.JTextField BDname2;
    private javax.swing.JToggleButton BTN_3;
    private javax.swing.JToggleButton BTN_R1;
    private javax.swing.JToggleButton BTN_R2;
    private javax.swing.JButton BTNclean;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenuItem jMenuSql1;
    private javax.swing.JMenuItem jMenuSql2;
    private javax.swing.JMenuItem jMenuSql3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTable tbTabla1;
    private javax.swing.JTable tbTabla2;
    private javax.swing.JTable tbTabla3;
    private javax.swing.JTabbedPane tpMenu;
    // End of variables declaration//GEN-END:variables
}
